import { abweb, acess, sunbuds, mans } from "@/assets/experience";
export const experiences = [
  {
    title: "Web Developer",
    company_name: "Mans srl",
    reason_left: {
      en: "Left to expand my skills and gain a broader perspective abroad",
      it: "Lasciato per ampliare le mie competenze e ottenere una prospettiva più ampia all'estero",
      jp: "スキルを広げ、海外でより広い視野を得るために退職しました。",
    },
    icon: mans,
    iconBg: "#E6DEDD",
    date: "May 2017 - Mar 2022",
    points: {
      en: [
        "Developed and maintained WordPress-based e-commerce sites, customizing HTML, CSS, and JavaScript to meet specific company' requirements.",
        "Used Google Ads and Google Analytics to drive targeted traffic and enhance site visibility, implementing SEO best practices that improved site rankings and online presence.",
        "Focused on responsive design, creating seamless multi-device experiences and ensuring high performance across all browsers.",
        "Collaborated with graphic designers, working with Photoshop and Illustrator to integrate custom visuals that aligned with the brand’s aesthetics.",
      ],
      it: [
        "Sviluppato e gestito siti e-commerce basati su WordPress, personalizzando HTML, CSS e JavaScript per soddisfare specifiche esigenze aziendali.",
        "Utilizzato Google Ads e Google Analytics per generare traffico mirato e migliorare la visibilità del sito, implementando le migliori pratiche SEO che hanno incrementato il posizionamento e la presenza online.",
        "Concentrato sul design responsive, creando esperienze fluide su più dispositivi e garantendo alte prestazioni su tutti i browser e device.",
        "Collaborato con designer grafici, utilizzando Photoshop e Illustrator per integrare elementi visivi personalizzati in linea con l'estetica del brand.",
      ],
      jp: [
        "WordPressをベースにしたeコマースサイトを開発および管理し、クライアントの特定の要件に合わせてHTML、CSS、JavaScriptをカスタマイズしました。",
        "Google広告とGoogleアナリティクスを活用してターゲットトラフィックを増加させ、サイトの視認性を向上させました。また、SEOのベストプラクティスを実装し、サイトのランキングとオンラインプレゼンスを改善しました。",
        "レスポンシブデザインに注力し、複数デバイスでシームレスな体験を提供し、すべてのブラウザで高いパフォーマンスを確保しました。",
        "グラフィックデザイナーと連携し、PhotoshopやIllustratorを使用して、ブランドの美的感覚に合わせたカスタムビジュアルを統合しました。",
      ],
    },
    techStack: [
      "WordPress -",
      "HTML -",
      "CSS -",
      "JavaScript -",
      "Google Ads -",
      "Google Analytics -",
      "SEMrush -",
      "Ahrefs -",
      "Hotjar -",
      "Photoshop -",
      "Illustrator",
    ],
  },
  {
    title: "Fullstack Developer (Co-Founder)",
    company_name: "Sunbuds srl",
    reason_left: {
      en: "Left to expand my skills and gain a broader perspective abroad",
      it: "Lasciato per ampliare le mie competenze e ottenere una prospettiva più ampia all'estero",
      jp: "スキルを広げ、海外でより広い視野を得るために退職しました。",
    },
    icon: sunbuds,
    iconBg: "#E6DEDD",
    date: "Apr 2019 - Feb 2022",
    points: {
      en: [
        "Created a full-featured e-commerce platform and blog from scratch, using Laravel to manage backend logic and MySQL for data storage and retrieval.",
        "Developed a CMS to streamline inventory and blog content management.",
        "Built interactive, responsive frontend components in Vue.js, styled with SASS and Bootstrap, to enhance the user experience.",
        "Designed with Figma to mirror an Amazon-inspired UI, creating a polished, professional customer experience.",
        "Integrated Stripe for secure payment processing, managing complex transactions within the Laravel backend for reliable, seamless payments.",
        "Conducted end-to-end testing with Selenium and API testing with Postman to ensure quality and functionality.",
        "Developed a customer engagement feature—a JavaScript-based game—allowing users to win discounts, adding a playful element to the platform.",
        "Deployed the application on Digital Ocean, managing server configuration and optimizing for performance in a production environment.",
      ],
      it: [
        "Creato una piattaforma e-commerce completa e un blog da zero, utilizzando Laravel per gestire la logica backend e MySQL per l'archiviazione e il recupero dei dati.",
        "Sviluppato un CMS per semplificare la gestione dell'inventario e dei contenuti del blog.",
        "Creato componenti frontend interattivi e responsive in Vue.js, stilizzati con SASS e Bootstrap, per migliorare l'esperienza utente.",
        "Progettato con Figma per replicare un'interfaccia ispirata ad Amazon, creando un'esperienza cliente professionale e curata.",
        "Integrato Stripe per l'elaborazione sicura dei pagamenti, gestendo transazioni complesse all'interno del backend di Laravel per garantire pagamenti affidabili e senza interruzioni.",
        "Condotto test end-to-end con Selenium e test API con Postman per garantire qualità e funzionalità.",
        "Sviluppato una funzione di coinvolgimento del cliente: un gioco basato su JavaScript che consente agli utenti di vincere sconti, aggiungendo un elemento ludico alla piattaforma.",
        "Distribuito l'applicazione su Digital Ocean, gestendo la configurazione del server e ottimizzando le prestazioni in un ambiente di produzione.",
      ],
      jp: [
        "Laravelを使用してバックエンドのロジックを管理し、MySQLでデータの保存と取得を行う、完全機能のeコマースプラットフォームとブログをゼロから作成しました。",
        "在庫とブログコンテンツ管理を効率化するためのCMSを開発しました。",
        "Vue.jsでインタラクティブでレスポンシブなフロントエンドコンポーネントを構築し、SASSとBootstrapでスタイリングして、ユーザー体験を向上させました。",
        "Figmaでデザインし、Amazon風のUIを再現して、洗練されたプロフェッショナルな顧客体験を構築しました。",
        "Stripeを統合して安全な支払い処理を実現し、Laravelのバックエンド内で複雑なトランザクションを管理して、信頼性の高いシームレスな支払いを提供しました。",
        "Seleniumを使用したエンドツーエンドテストとPostmanを使用したAPIテストを実施して、品質と機能性を確保しました。",
        "ユーザーが割引を獲得できるJavaScriptベースのゲームを開発し、プラットフォームに遊び心のある要素を追加しました。",
        "アプリケーションをDigital Oceanにデプロイし、サーバー構成を管理して、本番環境でのパフォーマンスを最適化しました。",
      ],
    },
    techStack: [
      "Laravel -",
      "PHP -",
      "SQL -",
      "Vue.js 2 -",
      "Stripe -",
      "Selenium -",
      "Figma -",
      "Postman -",
      "Bootstrap -",
      "HTML -",
      "CSS -",
      "Git",
    ],
  },
  {
    title: "Fullstack Developer",
    company_name: "Acess Pty ltd",
    reason_left: {
      en: "Left due to visa restrictions (6 months work limitation)",
      it: "Lasciato a causa di restrizioni sul visto (limite di lavoro di 6 mesi)",
      jp: "ビザの制限（6ヶ月の労働制限）のため退職しました。",
    },
    icon: acess,
    iconBg: "#E6DEDD",
    date: "Dec 2022 - Jul 2023",
    points: {
      en: [
        "Developed backend features using Laravel, focusing on efficient and modular MVC patterns that ensured a scalable and secure codebase, leveraging MySQL for robust data storage and retrieval.",
        "Created form management and automated user notification systems, including role-specific email notifications sent directly from the platform.",
        "Built responsive and interactive frontends using AngularJS with SASS and Bootstrap, ensuring cross- browser compatibility. Collaborated with designers using Figma for cohesive UI/UX implementation and user-centered design.",
        "Conducted API testing with Postman to ensure reliability and consistency of data handling across the application.",
        "Redesigned the homepage with a more modern aesthetic and functionality, integrating forms aligned with Australian legal requirements for the childcare industry.",
        "Utilized GitLab for version control and collaboration, coordinating with team members on feature development and code reviews to maintain a streamlined development process.",
      ],
      it: [
        "Sviluppato features backend utilizzando Laravel, concentrandomi su pattern MVC efficienti e modulari che garantissero un codice scalabile e sicuro, sfruttando MySQL per un'archiviazione e un recupero dati robusti.",
        "Creato sistemi di gestione dei moduli e notifiche utente automatizzate, inclusi avvisi email specifici per ruolo inviati direttamente dalla piattaforma.",
        "Creato front-end reattivi e interattivi utilizzando AngularJS con SASS e Bootstrap, garantendo la compatibilità tra browser. Collaborato con i designer tramite Figma per un'implementazione coerente di UI/UX e un design incentrato sull'utente.",
        "Condotto test API con Postman per garantire affidabilità e coerenza nella gestione dei dati all'interno dell'applicazione.",
        "Ridisegnata la homepage con un'estetica e funzionalità più moderne, integrando moduli conformi ai requisiti legali australiani per il settore dell'infanzia.",
        "Utilizzato GitLab per il controllo di versione e la collaborazione, coordinandomi con il team nello sviluppo di funzionalità e revisioni del codice per mantenere un processo di sviluppo fluido.",
      ],
      jp: [
        "Laravelを使用してバックエンドアーキテクチャを開発し、効率的でモジュール化されたMVCパターンに重点を置き、スケーラブルで安全なコードベースを実現しました。また、MySQLを活用して堅牢なデータの保存と取得を行いました。",
        "フォーム管理およびユーザー通知システムを作成し、プラットフォームから直接送信される役割別のメール通知を含みました。",
        "AngularJSを使用してSASSおよびBootstrapでレスポンシブでインタラクティブなフロントエンドを構築し、クロスブラウザ互換性を確保しました。また、Figmaを使用してデザイナーと連携し、統一感のあるUI/UXの実装とユーザー中心のデザインを実現しました。",
        "Postmanを使用してAPIテストを実施し、アプリケーション全体でのデータ処理の信頼性と一貫性を確保しました。",
        "保育業界向けのオーストラリア法規制に準拠したフォームを統合し、より現代的な美観と機能を備えたホームページを再設計しました。",
        "GitLabを活用してバージョン管理とコラボレーションを行い、機能開発やコードレビューでチームメンバーと調整し、効率的な開発プロセスを維持しました。",
      ],
    },
    techStack: [
      "Laravel -",
      "PHP -",
      "SQL -",
      "AngularJS -",
      "Figma -",
      "Postman -",
      "Azure -",
      "Bootstrap -",
      "HTML -",
      "CSS -",
      "Gitlab -",
      "Hubspot",
    ],
  },
  {
    title: "Fullstack Developer",
    company_name: "AbWeb ltd",
    reason_left: {
      en: "Left due to visa Expiring",
      it: "Lasciato a causa del visto in scadenza",
      jp: "ビザの期限切れのため退職しました",
    },
    icon: abweb,
    iconBg: "#E6DEDD",
    date: "Aug 2023 - Dec 2023",
    points: {
      en: [
        "Maintained existing web applications, using Laravel for backend processes and data handling, and JQuery to create dynamic, interactive elements on the frontend.",
        "Managed the integration timeline for the company’s app features into clients’ websites, balancing high- quality coding with realistic delivery schedules.",
        "Implemented responsive designs with CSS, ensuring cross-browser functionality and a cohesive user experience.",
        "Developed functionality within Laravel to restrict visibility of certain products, ensuring only specific user groups could view reserved items. Integrated this feature seamlessly with the existing BigCommerce codebase, tailoring it to meet unique client requirements.",
        "Assigned tasks and provided guidance to junior developers with less experience.",
      ],
      it: [
        "Mantenimento delle applicazioni web esistenti, utilizzando Laravel per i processi backend e la gestione dei dati, e JQuery per creare elementi dinamici e interattivi nel frontend.",
        "Gestito la tempistica di integrazione delle funzionalità dell'app aziendale nei siti web dei clienti, bilanciando codice di alta qualità con tempi di consegna realistici.",
        "Implementato design responsivi con CSS, garantendo funzionalità cross-browser e un'esperienza utente coerente.",
        "Sviluppato funzionalità all'interno di Laravel per limitare la visibilità di determinati prodotti, garantendo che solo gruppi di utenti specifici potessero visualizzare gli articoli riservati. Integrato questa funzionalità senza problemi con l'attuale codebase di BigCommerce, adattandola per soddisfare le esigenze specifiche del cliente.",
        "Delegato tasks e fornito indicazioni a sviluppatori junior con meno esperienza.",
      ],
      jp: [
        "既存のWebアプリケーションを維持・強化し、バックエンドのプロセスとデータ処理にLaravelを使用し、フロントエンドで動的でインタラクティブな要素を作成するためにJQueryを使用しました。",
        "会社のアプリ機能をクライアントのウェブサイトに統合するスケジュールを管理し、高品質なコードと現実的な納期を調整しました。",
        "CSSを使用してレスポンシブデザインを実装し、クロスブラウザ機能と一貫したユーザー体験を保証しました。",
        "Laravel内で特定の製品の表示を制限する機能を開発し、特定のユーザーグループのみが予約商品を表示できるようにしました。この機能は既存のBigCommerceのコードベースとシームレスに統合し、クライアントの特定の要件に合わせてカスタマイズしました。",
        "経験の少ないジュニア開発者にタスクを割り当て、指導を行いました。",
      ],
    },
    techStack: [
      "Laravel -",
      "PHP -",
      "SQL -",
      "JQuery -",
      "JavaScript -",
      "Postman -",
      "HTML -",
      "CSS -",
      "Git -",
      "BigCommerce",
    ],
  },
];
